@path = http://localhost:8080/api
@cookie = session_cookie=AYcoIVwerI7TrsaeG-jrBlf-ZyIZGm9N3DJrYdM-7VBq2hsDDPSXnwQUpgnjjTOXSpRAcGVbukczNXVri4jUpu7fLBfBtsX3tSI1z3OcRCbzYRdtTe4gsN7WjvKS8UTMohiP2HiUHLAatTAAmi3J_E3gS3UiSggt0hU9bhZonLeD23n8n6l11lYIB_hb7T4Rh-n3gzkVcePpqTKm87G0GDSM1F2WOzx8Q58LosKVrJnratGl

### GET Categories
GET {{path}}/categories

### Add Category
POST {{path}}/categories
Content-Type: application/json
Cookie: {{cookie}}

{
    "name": "Category#1"
}

### Update Categories
PUT {{path}}/categories/1

{
    "name": "CategoryUpdated"
}

### GET Category
GET {{path}}/categories/1

### Add Category
POST {{path}}/categories
Content-Type: application/json

{
    "name": "Category#2"
}

### GET Category
GET {{path}}/categories/2

### GET Categories
GET {{path}}/categories

### Add Product
POST {{path}}/products
Content-Type: application/json

{
    "name": "Name#1",
    "description": "",
    "categoryId": 1,
    "price": "1"
}

### GET Product
GET {{path}}/products/1

### Update Product
PUT {{path}}/products/1
Content-Type: application/json

{
    "name": "Name#112",
    "description": "descr",
    "categoryId": 2,
    "price": "100"
}

### GET Product
GET {{path}}/products/1

### DELET Product
DELETE  {{path}}/products/1

### GET Product
GET {{path}}/products/1

### GET Product
DELETE  {{path}}/categories/1

### GET Products
GET {{path}}/products

### GET Categories
GET {{path}}/categories

### Create User
POST {{path}}/sign-up
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "PAsW0RD121414623!"
}

### Login User
POST {{path}}/sign-in
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "PAsW0RD121414623!"
}

### Add To Cart
POST {{path}}/carts
Content-Type: application/json

{
    "productId": 1,
    "userId": 1
}

### GET My Cart
GET {{path}}/carts/1

### DELETE Item from cart
DELETE {{path}}/carts?id=1&userId=1