@path = http://localhost:8000/api

### Create User
POST {{path}}/sign-up
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "PAsW0RD121414623!"
}

### Login User
# @name loginUser
POST {{path}}/sign-in
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "PAsW0RD121414623!"
}

@cookie = {{loginUser.response.headers.Set-Cookie}}

### GET User Profile
GET {{path}}/users/me
Cookie: {{cookie}}

### GET Categories
GET {{path}}/categories
Cookie: {{cookie}}

### Add Category
POST {{path}}/categories
Content-Type: application/json
Cookie: {{cookie}}

{
    "name": "Category#1"
}

### Update Categories
PUT {{path}}/categories/1
Cookie: {{cookie}}

{
    "name": "CategoryUpdated#1"
}

### GET Category
GET {{path}}/categories/oJjl1DE
Cookie: {{cookie}}

### Add Category
POST {{path}}/categories
Content-Type: application/json
Cookie: {{cookie}}

{
    "name": "Category#2"
}

### GET Category
GET {{path}}/categories/2
Cookie: {{cookie}}

### GET Categories
GET {{path}}/categories
Cookie: {{cookie}}

### Add Product
POST {{path}}/products
Content-Type: application/json
Cookie: {{cookie}}

{
    "name": "Name#1",
    "description": "",
    "categoryId": 1,
    "price": "1"
}

### GET Product
GET {{path}}/products/1
Cookie: {{cookie}}

### Update Product
PUT {{path}}/products/1
Content-Type: application/json
Cookie: {{cookie}}

{
    "name": "Name#112",
    "description": "descr",
    "categoryId": 2,
    "price": "100"
}

### GET Product
GET {{path}}/products/1
Cookie: {{cookie}}

### DELET Product
DELETE  {{path}}/products/1
Cookie: {{cookie}}

### GET Product
GET {{path}}/products/1
Cookie: {{cookie}}

### DELETE Category
DELETE  {{path}}/categories/1
Cookie: {{cookie}}

### GET Products
GET {{path}}/products
Cookie: {{cookie}}

### GET Categories
GET {{path}}/categories
Cookie: {{cookie}}

### Add To Cart
POST {{path}}/carts
Content-Type: application/json
Cookie: {{cookie}}

{
    "productId": 1
}

### GET My Cart
GET {{path}}/carts/my
Cookie: {{cookie}}

### DELETE Item from cart
DELETE {{path}}/carts/1
Cookie: {{cookie}}

### Add Order from cart
POST {{path}}/orders/from-cart
Content-Type: application/json
Cookie: {{cookie}}

### Add Order
POST {{path}}/orders
Content-Type: application/json
Cookie: {{cookie}}

{
    "productIds": [
        1, 2, 1
    ]
}

### Admin section
### Login User
# @name loginAdmin
POST {{path}}/sign-in
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "Pas0WotRhD9!6&aPL"
}

@cookieAdmin = {{loginAdmin.response.headers.Set-Cookie}}

### GET All User Session with id 1
GET {{path}}/sessions/2
Cookie: {{cookieAdmin}}