@path = http://localhost:8080/api
@cookie = session_cookie=AV0IQjViQzV8hnGnGKQoqhNMkbwxxE0-LA6wPBMhaDInOBryGU8ouyAbVJWG-pLZE-QqEgZBEzpZ0W7eHX3lMfuAc3X_2xJRCKOT4HmrTvNym6hC39XvufueH0AL1T2mQ5AFff4-kAq0lskd-p38-Ak3irGJiPgg4HOPc6qXcEqztio43NntIstNWmwBFrDg9XfRLS3oKMNGndVH6uInOIchLGoD85BNwCJAdoWqSC3cuG94

### GET Categories
GET {{path}}/categories

### Add Category
POST {{path}}/categories
Content-Type: application/json
Cookie: {{cookie}}

{
    "name": "Category#1"
}

### Update Categories
PUT {{path}}/categories/1

{
    "name": "CategoryUpdated"
}

### GET Category
GET {{path}}/categories/1

### Add Category
POST {{path}}/categories
Content-Type: application/json

{
    "name": "Category#2"
}

### GET Category
GET {{path}}/categories/2

### GET Categories
GET {{path}}/categories

### Add Product
POST {{path}}/products
Content-Type: application/json

{
    "name": "Name#1",
    "description": "",
    "categoryId": 1,
    "price": "1"
}

### GET Product
GET {{path}}/products/1

### Update Product
PUT {{path}}/products/1
Content-Type: application/json

{
    "name": "Name#112",
    "description": "descr",
    "categoryId": 2,
    "price": "100"
}

### GET Product
GET {{path}}/products/1

### DELET Product
DELETE  {{path}}/products/1

### GET Product
GET {{path}}/products/1

### GET Product
DELETE  {{path}}/categories/1

### GET Products
GET {{path}}/products

### GET Categories
GET {{path}}/categories

### Create User
POST {{path}}/sign-up
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "PAsW0RD121414623!"
}

### Login User
POST {{path}}/sign-in
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "PAsW0RD121414623!"
}

### Add To Cart
POST {{path}}/carts
Content-Type: application/json

{
    "productId": 1,
    "userId": 1
}

### GET My Cart
GET {{path}}/carts/1

### DELETE Item from cart
DELETE {{path}}/carts?id=1&userId=1