# Server configurations
server:
  host: "localhost"
  port: 8123
  cookieHashKey: "BFaZsdAaVm1e4o!1i&l42@kxsb+!a/#^"
  idSalt: "9suidhfgiusgoisnd89sfw89qb"

# Database migration credentials
databaseMigration:
  user: "root"
  pass: ""

# Database credentials
database:
  name: "restaurant_db_test"
  user: "testowy12345"
  pass: "testowe12345"